name: Deploy to DockerHub

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag latest (default compose)
        run: |
          docker compose build
          docker tag hello-world_app etapau/hello-world:latest

      - name: Push latest tag
        run: docker push etapau/hello-world:latest

      - name: Build and tag md (md compose)
        run: |
          docker compose -f docker-compose-md.yml build
          docker tag hello-world_app etapau/hello-world:md

      - name: Push md tag
        run: docker push etapau/hello-world:md
