name: Deploy to DockerHub

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push latest (default compose)
        run: |
          docker compose build
          docker compose push
      - name: Build and Push md (md compose)
        run: |
          docker compose -f docker-compose-md.yml build
          docker compose -f docker-compose-md.yml push