name: Deploy to Quay

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - run: docker-compose build
      - run: docker tag docker.io/library/hello-world_app quay.io/mechanicode/azure-interview:broken
      - run: docker push quay.io/mechanicode/azure-interview:broken
